version: '2'
services:
  dev:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - TEST_NAMESPACE
      - TEST_REGION
    volumes:
      - ./:/code
    command:
      - composer
      - ci
